## Univariate Feature Selection

In [ ]:
from pandas import read_csv
import pandas as pd
from numpy import set_printoptions
from sklearn.feature_selection import SelectKBest
from sklearn.feature_selection import chi2


In [ ]:
filename="/content/pima-indians-diabetes.data.csv"
names=["preg","plas","pres","skin","test","mass","pedi","age","class"]
dataframe=read_csv(filename,names=names)
array=dataframe.values
dataframe.head()

preg  plas  pres  skin  test  mass   pedi  age  class
0     6   148    72    35     0  33.6  0.627   50      1
1     1    85    66    29     0  26.6  0.351   31      0
2     8   183    64     0     0  23.3  0.672   32      1
3     1    89    66    23    94  28.1  0.167   21      0
4     0   137    40    35   168  43.1  2.288   33      1

In [ ]:
X=array[:,0:8]
Y=array[:,8]
test=SelectKBest(score_func=chi2,k=5)
fit=test.fit(X,Y)
set_printoptions(precision=4)
print(fit.scores_)
features=fit.transform(X)

[ 111.5197 1411.887    17.6054   53.108  2175.5653  127.6693    5.3927
  181.3037]


In [ ]:
names

['preg', 'plas', 'pres', 'skin', 'test', 'mass', 'pedi', 'age', 'class']

In [ ]:
type(test)

sklearn.feature_selection._univariate_selection.SelectKBest

In [ ]:
x=pd.DataFrame(fit.scores_).T

In [ ]:
x

0            1          2  ...           5         6           7
0  111.519691  1411.887041  17.605373  ...  127.669343  5.392682  181.303689

[1 rows x 8 columns]

In [ ]:
x.columns=names[:8]
x

preg         plas       pres  ...        mass      pedi         age
0  111.519691  1411.887041  17.605373  ...  127.669343  5.392682  181.303689

[1 rows x 8 columns]

## Recursive Feature Elimination

In [ ]:
from pandas import read_csv
from sklearn.feature_selection import RFE
from sklearn.linear_model import LogisticRegression

filename="/content/pima-indians-diabetes.data.csv"
names=["preg","plas","pres","skin","test","mass","pedi","age","class"]
dataframe=read_csv(filename,names=names)
array=dataframe.values
X=array[:,0:8]
Y=array[:,8]
model=LogisticRegression(max_iter=400)
rfe=RFE(model)
fit=rfe.fit(X,Y)

In [ ]:
fit.n_features_

4

In [ ]:
fit.support_

array([ True,  True, False, False, False,  True,  True, False])

In [ ]:
names

['preg', 'plas', 'pres', 'skin', 'test', 'mass', 'pedi', 'age', 'class']

In [ ]:
fit.ranking_

array([1, 1, 3, 5, 4, 1, 1, 2])

## Feature Importance using Decision Tree

In [ ]:
from pandas import read_csv
from sklearn.tree import DecisionTreeClassifier

filename="/content/pima-indians-diabetes.data.csv"
names=["preg","plas","pres","skin","test","mass","pedi","age","class"]
dataframe=read_csv(filename,names=names)
array=dataframe.values
X=array[:,0:8]
Y=array[:,8]
model=DecisionTreeClassifier()
model.fit(X,Y)
print(model.feature_importances_)

[0.0625 0.3097 0.0801 0.029  0.0489 0.2415 0.1126 0.1155]


In [ ]:
names

['preg', 'plas', 'pres', 'skin', 'test', 'mass', 'pedi', 'age', 'class']